config/routes.rb
MixTapeApp::Application.routes.draw do
  resources :visitors

  get "home/index"

  resources :genres

  resources :mixtapes

  resources :users

  resources :songs

  resources :albums

  resources :artists

  match '/login' => 'session#new', :via => :get
  match '/login' => 'session#create', :via => :post
  match '/logout' => 'session#destroy', :via => :delete

  root :to => 'home#index'

end

app/models/artist.rb
class Artist < ActiveRecord::Base
  attr_accessible :name, :songs_attributes
  has_many :songs
  has_many :albums, :through => :songs
  validates :name, :presence => true
  accepts_nested_attributes_for :songs, :allow_destroy => true
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  # GET /artists
  # GET /artists.json
  def index
    @artists = Artist.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @artists }
    end
  end

  # GET /artists/1
  # GET /artists/1.json
  def show
    @artist = Artist.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @artist }
    end
  end

  # GET /artists/new
  # GET /artists/new.json
  def new
    @artist = Artist.new
    5.times {@artist.songs.build}

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @artist }
    end
  end

  # GET /artists/1/edit
  def edit
    @artist = Artist.find(params[:id])
  end

  # POST /artists
  # POST /artists.json
  def create
    @artist = Artist.new(params[:artist])

    respond_to do |format|
      if @artist.save
        format.html { redirect_to @artist, notice: 'Artist was successfully created.' }
        format.json { render json: @artist, status: :created, location: @artist }
      else
        format.html { render action: "new" }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /artists/1
  # PUT /artists/1.json
  def update
    @artist = Artist.find(params[:id])

    respond_to do |format|
      if @artist.update_attributes(params[:artist])
        format.html { redirect_to @artist, notice: 'Artist was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /artists/1
  # DELETE /artists/1.json
  def destroy
    @artist = Artist.find(params[:id])
    @artist.destroy

    respond_to do |format|
      format.html { redirect_to artists_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/views/artists/_form.html.erb
<%= form_for(@artist) do |f| %>
  <%= render :partial => 'shared/errors', :locals => {:model => @artist} %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  <%= render :partial => 'shared/song', :locals => {:form => f} %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/artists/edit.html.erb
<h2>Editing artist</h2>

<%= render 'form' %>

<%= link_to 'Show', @artist %> |
<%= link_to 'Back', artists_path %>

app/views/artists/index.html.erb
<h2>Artists</h2>

<table class="table table-hover">
  <tr>
    <th>Name</th>
    <th>Actions</th>
  </tr>

  <% @artists.each do |artist| %>
    <tr>
      <td><%= link_to artist.name, artist %></td>
      <td>
        <%= link_to 'Edit', edit_artist_path(artist), :class => "btn btn-mini" %>
        <%= link_to 'Destroy', artist, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-mini btn-danger" %>
      </td>
    </tr>
  <% end %>
</table>

<%= link_to 'New Artist', new_artist_path, :class => "btn btn-primary" %>
<br />
<br />

app/views/artists/new.html.erb
<h2>New artist</h2>

<%= render 'form' %>

<%= link_to 'Back', artists_path %>

app/views/artists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @artist.name %>
</p>


<%= link_to 'Edit', edit_artist_path(@artist) %> |
<%= link_to 'Back', artists_path %>