config/routes.rb
MixTapeApp::Application.routes.draw do
  resources :visitors

  get "home/index"

  resources :genres

  resources :mixtapes

  resources :users

  resources :songs

  resources :albums

  resources :artists

  match '/login' => 'session#new', :via => :get
  match '/login' => 'session#create', :via => :post
  match '/logout' => 'session#destroy', :via => :delete

  root :to => 'home#index'

end

app/models/mixtape.rb
class Mixtape < ActiveRecord::Base
  attr_accessible :name, :song_ids
  has_and_belongs_to_many :songs
  has_and_belongs_to_many :users  
  validates :name, :presence => true
end

app/controllers/mixtapes_controller.rb
class MixtapesController < ApplicationController
  # GET /mixtapes
  # GET /mixtapes.json
  def index
    @mixtapes = Mixtape.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @mixtapes }
    end
  end

  # GET /mixtapes/1
  # GET /mixtapes/1.json
  def show
    @mixtape = Mixtape.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @mixtape }
    end
  end

  # GET /mixtapes/new
  # GET /mixtapes/new.json
  def new
    @mixtape = Mixtape.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @mixtape }
    end
  end

  # GET /mixtapes/1/edit
  def edit
    @mixtape = Mixtape.find(params[:id])
  end

  # POST /mixtapes
  # POST /mixtapes.json
  def create
    @mixtape = Mixtape.new(params[:mixtape])

    respond_to do |format|
      if @mixtape.save
        format.html { redirect_to @mixtape, notice: 'Mixtape was successfully created.' }
        format.json { render json: @mixtape, status: :created, location: @mixtape }
      else
        format.html { render action: "new" }
        format.json { render json: @mixtape.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /mixtapes/1
  # PUT /mixtapes/1.json
  def update
    @mixtape = Mixtape.find(params[:id])

    if params[:mixtape][:song_ids].nil?
      @mixtape.songs = []
    end

    respond_to do |format|
      if @mixtape.update_attributes(params[:mixtape])
        format.html { redirect_to @mixtape, notice: 'Mixtape was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @mixtape.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mixtapes/1
  # DELETE /mixtapes/1.json
  def destroy
    @mixtape = Mixtape.find(params[:id])
    @mixtape.destroy

    respond_to do |format|
      format.html { redirect_to mixtapes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/mixtapes_helper.rb
module MixtapesHelper
end

app/views/mixtapes/_form.html.erb
<%= form_for @mixtape, :html => { :class => 'form-horizontal' } do |f| %>
  <%= render :partial => 'shared/errors', :locals => {:model => @mixtape} %>
  
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>

  <%= render :partial => 'shared/song_list', :collection => Song.all, :as => :song,
             :locals => {:parent => @mixtape, :name => 'mixtape'} %>

  <br />
  <div class="actions clear">
    <%= f.submit nil, :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/mixtapes/edit.html.erb
<h2>Editing mixtape</h2>

<%= render 'form' %>

<%= link_to 'Show', @mixtape %> |
<%= link_to 'Back', mixtapes_path %>

app/views/mixtapes/index.html.erb
<h2>Mixtapes</h2>

<table class="table table-hover">
  <tr>
    <th>Name</th>
    <th>Actions</th>
  </tr>

  <% @mixtapes.each do |mixtape| %>
    <tr>
      <td><%= link_to mixtape.name, mixtape %></td>
      <td>
        <%= link_to 'Edit', edit_mixtape_path(mixtape), :class => "btn btn-mini" %>
        <%= link_to 'Destroy', mixtape, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-mini btn-danger" %>
      </td>
    </tr>
  <% end %>
</table>

<%= link_to 'New Mixtape', new_mixtape_path, :class => "btn btn-primary" %>
<br />
<br />

app/views/mixtapes/new.html.erb
<h2>New mixtape</h2>

<%= render 'form' %>

<%= link_to 'Back', mixtapes_path %>

app/views/mixtapes/show.html.erb
<p id="notice"><%= notice %></p>

  <h3>Mixtape: <%= @mixtape.name %></h3>

<%= render :partial => 'shared/song_show', :collection => @mixtape.songs, :as => :song %>

<%= link_to 'Edit', edit_mixtape_path(@mixtape) %> |
<%= link_to 'Back', mixtapes_path %>