config/routes.rb
MixTapeApp::Application.routes.draw do
  resources :visitors

  get "home/index"

  resources :genres

  resources :mixtapes

  resources :users

  resources :songs

  resources :albums

  resources :artists

  match '/login' => 'session#new', :via => :get
  match '/login' => 'session#create', :via => :post
  match '/logout' => 'session#destroy', :via => :delete

  root :to => 'home#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MixTapeApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="app">
  <div id="app-header">
    <h1>MixTape 2.0</h1>
    <ul class="nav nav-tabs">
      <li class="<%= 'active' if params[:controller] == 'home' %>"><%= link_to "Home", root_path %></li>
      <li class="<%= 'active' if params[:controller] == 'artists' %>"><%= link_to "Artists", artists_path %><li>
      <li class="<%= 'active' if params[:controller] == 'albums' %>"><%= link_to "Albums", albums_path %></li>
      <li class="<%= 'active' if params[:controller] == 'songs' %>"><%= link_to "Songs", songs_path %></li>
      <li class="<%= 'active' if params[:controller] == 'genres' %>"><%= link_to "Genres", genres_path %></li>
      <li class="<%= 'active' if params[:controller] == 'mixtapes' %>"><%= link_to "Mixtapes", mixtapes_path %></li>
      <li class="<%= 'active' if params[:controller] == 'users' %>"><%= link_to "Users", users_path %></li>
      <% if !@user.present? %>
        <li style="float: right" class="<%= 'active' if (params[:controller] == 'session') && (params[:action] == 'new') %>"><%= link_to "Login", login_path %></li>
      <% else %>
        <!-- <li style="float: right" class="<%= 'active' if (params[:controller] == 'session') && (params[:action] == 'destroy') %>"><%= link_to @user.email, logout_path, :method => :delete %></li> -->
        <li style="float: right" class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">
            <%= @user.email %>
            <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li>
              <%= link_to "Logout", logout_path, :method => :delete %>
            </li>
          </ul>
        </li>
      <% end %>
    </ul>
  </div>
	<div id="content"><%= yield %></div>
	<div id="footer">(c) 2012 MixTape Inc.</div>
</div>

</body>
</html>